---
title: "O2 analysis"
author: LMM
format: html
---
# Preliminaries

```{r}
#| label: packages
#| message: false
#| warning: false
library(tidyverse)
library(vegan)
library(knitr)
library(patchwork)
library(DT)
```

```{r}
#| label: directories
#| echo: false

ifelse(!dir.exists("figures"),
       dir.create("figures"),
       FALSE)

ifelse(!dir.exists("supplementary"),
       dir.create("supplementary"),
       FALSE)
```



```{r}
#| label: data
ponchos_raw <- read.csv("data/ponchos_master.csv")

shoot_den <- read.csv("data/shoot_density.csv")
```


```{r}
O2_init_avg <- ponchos_raw |> 
  filter(Month == "November" & !is.na(O2_0)) |> 
  group_by(light) |> 
  summarise(avg_O2 = mean(O2_0),
            sd_O2 = sd(O2_0))
```

# Oxygen

First we'll correct the $[O_2]$ in the chambers:

$$
\Delta O_2 = [O_2]_{tf}- mean([O_2]_{t0})
$$
$$
x \frac{mg}{L}O_2 \cdot \text{Volume measured} (L) \cdot \frac{1}{time (h)}  \cdot \frac{1g}{1000 mg} O_2 \cdot \frac{1mol}{31.99 g}O_2 \cdot \frac{1000000 \mu mol}{mol} = x\frac{\mu mol}{h}O_2 
$$

$$
\Delta [O_2] = [O_2]-mean([O_2]_{controls})
$$




```{r}
ponchos_data <- ponchos_raw |> 
  filter(!(Observation %in% c("t0", "rock"))) |>
  mutate(t0 = as.POSIXct(t0, format = "%H:%M"),
         tf = as.POSIXct(tf, format = "%H:%M"),
         total_time = as.numeric(tf - t0),
         Posidonia = as.factor(Posidonia),
         Chondrilla = as.factor(Chondrilla),
         light = as.factor(light),
         delta_O2 = ifelse(
           Month == "May",
           O2_f-O2_0,
           ifelse(
             light == 1,
             O2_f-O2_init_avg$avg_O2[2],
             O2_f-O2_init_avg$avg_O2[1]
           )
         ),
         dw = ifelse(
           is.na(dw_rhizome),
           dw_leaves + dw_sponge,
           dw_leaves + dw_sponge + dw_rhizome
         ),
         unc_rate_h = (delta_O2*volume*1000)/(31.99*total_time))

O2_ctrl_avg <- ponchos_data |> 
  filter(Observation == "Control") |> 
  group_by(light, Month) |> 
  summarise(ctrl_rate = mean(unc_rate_h))
        

ponchos_data <-  ponchos_data |> 
  filter(Observation %in% c("Posidonia", "Chondrilla", "Association")) |>
  mutate(cor_rate_h = case_when(
    Month == "November" & light == 1 ~ unc_rate_h - O2_ctrl_avg$ctrl_rate[4],
    Month == "November" & light == 0 ~ unc_rate_h - O2_ctrl_avg$ctrl_rate[2],
    Month == "May" & light == 1 ~ unc_rate_h - O2_ctrl_avg$ctrl_rate[3],
    TRUE ~ unc_rate_h - O2_ctrl_avg$ctrl_rate[1]),
    O2_rate = cor_rate_h/dw
  )
```

## Permanova tests

```{r permanova-net-photo}
set.seed(1)

perm_photo <- adonis(formula = O2_rate ~ Observation * Month,
                      data = ponchos_data[ponchos_data$light == 1,],
                        method = "euclidean")
perm_photo$aov.tab
```


```{r permanova-respiration}
set.seed(1)

perm_resp <- adonis(formula = O2_rate ~ Observation * Month,
                      data = ponchos_data[ponchos_data$light == 0 & ponchos_data$O2_rate < 0,],
                        method = "euclidean")
perm_resp$aov.tab
```

## Pairwise-tests

```{r pairw-net-photo}
suppt1 <- ponchos_data |> 
  mutate(inter =paste(ponchos_data$Month,"-",ponchos_data$Observation, sep = "")) |> 
    filter(light == 1) |> 
  select(O2_rate, inter) |> 
  {\(x) aov(O2_rate~inter,
                         data = x)}() |> 
  TukeyHSD() 


 ponchos_data |> 
  mutate(inter =paste(ponchos_data$Month,"-",ponchos_data$Observation, sep = "")) |> 
    filter(light == 1) |> 
  select(O2_rate, inter) |> 
    group_by(inter) |> 
    summarise(mean(O2_rate),
              sd(O2_rate
                 ))
```

```{r}
sink("supplementary/supp_table_1.md")

suppt1$inter |> 
  as.data.frame() |> 
  rownames_to_column("Combination") |> 
  kable(format = "markdown",
        col.names = c("Combination",
                      "Difference",
                      "Lower value",
                      "Upper value",
                      "Adjusted p"),
        caption = "test")

sink()
```


```{r pairw-resp}
suppt2 <- ponchos_data |> 
  mutate(inter =paste(ponchos_data$Month,"-",ponchos_data$Observation, sep = "")) |> 
    filter(light == 0) |> 
  filter(O2_rate < 0) |>
  select(O2_rate, inter) |> 
  {\(x) aov(O2_rate~inter,
                         data = x)}() |> 
  TukeyHSD()


  ponchos_data |> 
  mutate(inter =paste(ponchos_data$Month,"-",ponchos_data$Observation, sep = "")) |> 
    filter(light == 0) |> 
    filter(O2_rate < 0) |>
  select(O2_rate, inter) |> 
    group_by(inter) |> 
    summarise(mean(O2_rate))
```

```{r}
sink("supplementary/supp_table_2.md")

suppt2$inter |> 
  as.data.frame() |> 
  rownames_to_column("Combination") |> 
  kable(format = "markdown",
        col.names = c("Combination",
                      "Difference",
                      "Lower value",
                      "Upper value",
                      "Adjusted p"),
        caption = "test")

sink()
```


```{r}
#| code-fold: true
#| label: fig3 

f2a <- ponchos_data |> 
  rename(Season = Month) |> 
  mutate(Observation = fct_recode(Observation, 
                                  "Seagrass" = "Posidonia",
                                  "Sponge" = "Chondrilla"),
         Season = fct_recode(Season,
                             "Autumn" = "November",
                             "Spring" = "May")
         ) |> 
  mutate(Season = fct_relevel(Season, "Autumn"),
         Observation = fct_relevel(Observation,
                                   "Seagrass",
                                   "Sponge")
         ) |>
  filter(light == 1) |> 
  filter(replicate != "B") |>
  ggplot(aes(x = Observation, y = O2_rate, color = Season)) +
  geom_hline(yintercept = 0) +
  stat_summary(fun = mean,
               fun.min = function(x) mean(x) - sd(x),
               fun.max = function(x) mean(x) + sd(x),
               geom = "pointrange",
               shape = 3,
               position = position_dodge(width = 0.7)) +
  geom_point(alpha = 0.5,
             position = position_dodge(width = 0.7),
             size = 2.5) +
  scale_y_continuous(breaks = seq(-5, 25, by = 5)) +
  #annotate("text", y = 6, x = 2, label = "DRAFT", alpha = 0.2, size = 10) +
  labs(y = expression(paste(O[2]," flux (",mu,"mol ", g^-1, h^-1,")")),
       #x = "Treatment",
       tag = "A") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        legend.position = "bottom",
        axis.title.x=element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(color = "none")

f2b <- ponchos_data |> 
  rename(Season = Month) |>
  mutate(Observation = fct_recode(Observation, 
                                  "Seagrass" = "Posidonia",
                                  "Sponge" = "Chondrilla"),
         Season = fct_recode(Season,
                             "Autumn" = "November",
                             "Spring" = "May")
         ) |> 
  mutate(Season = fct_relevel(Season, "Autumn"),
         Observation = fct_relevel(Observation,
                                   "Seagrass",
                                   "Sponge")
         ) |>
  filter(replicate != "B") |>
  filter(light == 0) |> 
  filter(O2_rate < 0) |>
  ggplot(aes(x = Observation, y = O2_rate, color = Season)) +
  geom_hline(yintercept = 0) +
  stat_summary(fun = mean,
               fun.min = function(x) mean(x) - sd(x),
               fun.max = function(x) mean(x) + sd(x),
               geom = "pointrange",
               shape = 3,
               position = position_dodge(width = 0.7)) +
  geom_point(alpha = 0.5,
             position = position_dodge(width = 0.7),
             size = 2.5) +
  scale_y_continuous(breaks = seq(-5, 25, by = 5)) +
  #annotate("text", y = 6, x = 2, label = "DRAFT", alpha = 0.2, size = 10) +
  labs(y = expression(paste(O[2]," rate (",mu,"mol ", g^-1, h^-1,")")),
       x = "Observation",
       color = c("Autumn", "Spring"),
       tag = "B") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        axis.title.y=element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides(color = FALSE)

pooled_sd <- function(x, n) {sqrt(sum((x^2)/n))}

f2c <- ponchos_data |> 
  rename(Season = Month) |>
  mutate(Observation = fct_recode(Observation, 
                                  "Seagrass" = "Posidonia",
                                  "Sponge" = "Chondrilla"),
         Season = fct_recode(Season,
                             "Autumn" = "November",
                             "Spring" = "May")
         ) |> 
  mutate(Season = fct_relevel(Season, "Autumn"),
         Observation = fct_relevel(Observation,
                                   "Seagrass",
                                   "Sponge")
         ) |>
  filter(replicate != "B") |> 
  filter(!(O2_rate > 0 & light == 0)) |>
  group_by(Season, light, Observation) |> 
  summarise(p_mean = mean(O2_rate), p_sd = sd(O2_rate), n = n()) |> 
  group_by(Season, Observation) |> 
  summarise(gross = diff(p_mean),
            gross_sd = pooled_sd(x = p_sd, n = n)) |> 
  ggplot(aes(x = Observation, y = gross, color = Season)) +
  geom_hline(yintercept = 0) +
  geom_pointrange(aes(ymin = gross-gross_sd,
                  ymax = gross+gross_sd),
                  position = position_dodge(0.5),
                  shape = 3,
                  size = 1) +
  labs(y = expression(paste(O[2]," flux (mmol ", g^-1, h^-1,")")),
       #x = "Treatment",
       tag = "C") +
  #annotate("text", y = 12, x = 2, label = "DRAFT", alpha = 0.2, size = 10) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        legend.position = "bottom",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  guides()

f2a + f2b + f2c + plot_layout(guides = 'collect') &
  theme(legend.position='bottom') & ylim(-6, 28)

ggsave("figures/fig3.svg", width = 169, height = 120, units = "mm")
#ggsave("figures/fig3.png", width = 169, height = 120, units = "mm")
```

```{r}
#| echo: false
ponchos_data |> 
  rename(Season = Month) |> 
  mutate(Observation = fct_recode(Observation, 
                                  "Seagrass" = "Posidonia",
                                  "Sponge" = "Chondrilla")) |> 
  mutate(Season = fct_relevel(Season, "November"),
         Observation = fct_relevel(Observation,
                                   "Seagrass",
                                   "Sponge")
         ) |> 
  filter(replicate != "B") |>
  summarise(mean(O2_rate), sd(O2_rate), n(),.by = c(Observation, Season, light)) |> 
  datatable(options = list(pageLength = 12))
```


Our dark and light incubations are decoupled, but we can grossly estimate gross photosynthesis by adding the oxygen rates of the dark chambers to the rates of the light chambers

```{r gross-photosynthesis}
#| code-fold: true
pooled_sd <- function(x, n) {sqrt(sum((x^2)/n))}

ponchos_data |> 
  filter(replicate != "B") |> 
  filter(!(O2_rate > 0 & light == 0)) |>
  group_by(Month, light, Observation) |> 
  summarise(p_mean = mean(O2_rate), p_sd = sd(O2_rate), n = n()) |> 
  group_by(Month, Observation) |> 
  summarise(gross = diff(p_mean),
            gross_sd = pooled_sd(x = p_sd, n = n)) |> 
  ggplot(aes(x = Observation, y = gross, shape = Month, color = Month)) +
  geom_pointrange(aes(ymin = gross-gross_sd,
                  ymax = gross+gross_sd),
                  position = position_dodge(0.5),
                  size = 1) +
  labs(y = expression(paste(O[2]," rate (mmol ", g^-1, h^-1,")")),
       x = "Treatment") +
  annotate("text", y = 12, x = 2, label = "DRAFT", alpha = 0.2, size = 10) +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        legend.position = "bottom")
```

```{r}
ponchos_data |> 
  filter(replicate != "B" & Observation != "Posidonia") |> 
    filter(!(O2_rate > 0 & light == 0)) |>
  #group_by(Month, light, Observation) |> 
  summarise(p_mean = mean(O2_rate), 
            p_sd = sd(O2_rate), 
            n = n(),
            .by = c(Month, light, Observation)) |> 
  pivot_wider(values_from = p_mean,
              names_from = light,
              id_cols = -c(p_sd, n)) |> 
  mutate(ratio = (`1` - `0`)/`0`)
```

```{r}
Posi <- shoot_den |> 
  group_by(Substrate) |> 
  summarise(Mean = mean(Shoots_m2),
            SD = sd(Shoots_m2),
            N = n())

ponchos_data |>
  filter(Observation != "Chondrilla" & replicate != "B") |> 
  filter(!(light == 0 & chamber == "Posidonia-May" & O2_rate > 0)) |> 
  mutate(day = (O2_rate*24)/1e3) |> 
  group_by(Observation, Month, light) |> 
  summarize(mean_day = mean(day),
            sd_day = sd(day),
            n_day = n()) |>
  mutate(dasu = ifelse(Observation == "Posidonia",
                mean_day * Posi[Posi$Substrate == "Posidonia","Mean"][[1]],
                mean_day * Posi[Posi$Substrate == "Posidonia_Chondrilla","Mean"][[1]])) |> 
  left_join(Posi, c("Observation" = "Substrate")) |> 
  mutate(dasu_sd = sqrt(sum((sd_day^2)/n_day) + ((SD^2)/N))) |> 
  select(Observation, light, dasu, dasu_sd)
```



